src/objects/Assignment__c.object
<CustomObject>
    <description>An assignment represent something that needs to get done as part of a Project.</description>
    <fields>
        <fullName>Owner_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prerequisite_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prerequisite Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Internal QA</fullName>
                </value>
                <value>
                    <fullName>Client Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Archived</fullName>
                    <isActive>false</isActive>
                    <label>Archived</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <isActive>false</isActive>
                    <label>Complete</label>
                </value>
                <value>
                    <fullName>Projected</fullName>
                    <isActive>false</isActive>
                    <label>Projected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>DATEVALUE( Start_DateTime__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_DateTime__c</fullName>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>Time-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LightningController.cls
/**
* @name LightningController
* @date 2018-03-19
* @description Apex methods used by Lightning Components
* @author MK Partners, Inc.
* @license https://github.com/mk-partners/lightning-project-time-management/blob/master/LICENSE
* @website https://github.com/mk-partners/lightning-project-time-management
**/
public class LightningController {

	@auraEnabled
	public static sObject saveRecord(sObject record){
		system.debug(JSON.serialize(record));
		upsert record;
		return record;
	}

	@auraEnabled
	public static Map<String,Object> initTimeLogger(String queryDate){
		//2018-03-02T05:24:18.104Z
		queryDate = queryDate.replace('T',' ').left(19);
		DateTime qd = DateTime.valueOf(queryDate);
		Integer offset = UserInfo.getTimezone().getOffset(qd);
		Datetime local = qd.addSeconds(offset/1000);

		system.debug(local);
		Map<String,Object> res = new Map<String,Object>();
		List<Project__c> projectList = new List<Project__c>();
		for ( Project__c p : [
			SELECT Id, Name, Account__c, Account__r.Status__c, 
			(
				SELECT Id, Name
				FROM Assignments__r
				WHERE Status__c != 'Approved'
				AND Owner_User__c = :UserInfo.getUserId()
				ORDER BY Name
			)
			FROM Project__c
			WHERE Id IN (
				SELECT Project__c
				FROM Assignment__c
				WHERE Owner_User__c = :UserInfo.getUserId()
				AND Status__c != 'Archived'
			)
			AND Status__c != 'Archived'
			ORDER BY Name
		]){
			projectList.add(p);
		}
		List<Time__c> timeList = new List<Time__c>();
		for ( Time__c t : [
			SELECT Id, Project__c, Assignment__c, Start_DateTime__c, End_DateTime__c, Notes__c,
				Project__r.Account__c, Project__r.Account__r.Status__c
			FROM Time__c
			WHERE Date__c = :local.date()
			AND OwnerId = :UserInfo.getUserId()
		]){
			timeList.add(t);
		}
		res.put('queryDate',local);
		res.put('timeList',timeList);
		res.put('projectList',projectList);
		system.debug(JSON.serialize(res));
		return res;
	}

}